## **Import important Libraries**

In [37]:
import torch
import numpy as np

### **create Tensor in Torch**

In [9]:
# Empty tensor with 3 dimensions
x1 = torch.empty(4, 2, 3)
print(x1)

tensor([[[-2.0384e-11,  4.5626e-41, -2.0384e-11],
         [ 4.5626e-41,  4.2139e-34,  4.1537e-34]],

        [[ 4.3044e-34,  5.3274e-34,  2.6045e-29],
         [ 2.6900e-35,  2.4267e-35,  3.9431e-34]],

        [[ 4.4255e-34,  3.0581e-29,  7.4043e-40],
         [ 1.1663e-38,  1.1663e-38,  2.9000e-29]],

        [[ 2.8405e-29,  6.9836e-34,  4.0936e-34],
         [ 8.3228e-40,  7.6737e-34,  2.6146e-35]]])
tensor([[[ 3.5854e-34,  0.0000e+00,  4.1857e-35],
         [ 0.0000e+00, -1.6259e+10,  4.5625e-41]],

        [[ 1.4013e-45,  0.0000e+00,  5.6052e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [10]:
# Random tensor with 2 dimensions
x2 = torch.rand(2, 2)
print(x2)

tensor([[0.5759, 0.3535],
        [0.2382, 0.1674]])
tensor([[0.6601, 0.7904],
        [0.6668, 0.2567]])


In [11]:
# Zeroes tensor with 2 dimensions
x3 = torch.zeros(2, 2)
print(x3)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [12]:
# Ones tensor with 2 dimensions
x4 = torch.ones(2, 2)
print(x4)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


### **Type of Tensor**

In [13]:
# default type of tensor is float32
x1.dtype

torch.float32

torch.float32

In [14]:
# you can set other type to tensor
x5 = torch.ones(2, 2, dtype=torch.int) # torch.int, torch.double, torch.float16
print(x5.dtype)

torch.int32
torch.int32


### **Size of Tensor**

In [15]:
x6 = torch.rand(2, 2)
print(x6.size())

torch.Size([2, 2])


### **Create tensor with list of data**

In [17]:
x7 = torch.tensor([2.5, 3, 1])
print(x7)

tensor([2.5000, 3.0000, 1.0000])


### **Basic Operations**

In [23]:
x8 = torch.rand(2, 2)
x9 = torch.rand(2, 2)

print(x8, x9)

# Addition
x10 = x9 + x8
x10 = torch.add(x9, x8)
x9.add_(x8)
print(x10, x9)

# Subtraction
x11 = x9 - x8
x11 = torch.sub(x9, x8)
x9.sub_(x8)
print(x11, x9)

# Multiplication
x12 = x9 * x8
x12 = torch.mul(x9, x8)
x9.mul_(x8)
print(x12, x9)

# Division
x12 = x9 / x8
x12 = torch.div(x9, x8)
x9.div_(x8)
print(x12, x9)

tensor([[0.1469, 0.4717],
        [0.8296, 0.3212]]) tensor([[0.9460, 0.7150],
        [0.3348, 0.7956]])
tensor([[1.0930, 1.1867],
        [1.1643, 1.1168]]) tensor([[1.0930, 1.1867],
        [1.1643, 1.1168]])
tensor([[0.9460, 0.7150],
        [0.3348, 0.7956]]) tensor([[0.9460, 0.7150],
        [0.3348, 0.7956]])
tensor([[0.1390, 0.3373],
        [0.2777, 0.2556]]) tensor([[0.1390, 0.3373],
        [0.2777, 0.2556]])
tensor([[0.9460, 0.7150],
        [0.3348, 0.7956]]) tensor([[0.9460, 0.7150],
        [0.3348, 0.7956]])


### **Tensor Slicing**

In [27]:
x13 = torch.rand(5, 3)
print(x13)

print(x13[:, 0]) # All rows and column 0

print(x13[1, :]) # row 1 and all columns

print(x13[1, 1]) # actual element
print(x13[1, 1].item()) # if tensor have one element, you can use .item() to get actual value

tensor([[0.3073, 0.4964, 0.4810],
        [0.9046, 0.5382, 0.5784],
        [0.4814, 0.1969, 0.1082],
        [0.5659, 0.7731, 0.3610],
        [0.2770, 0.0994, 0.5931]])
tensor([0.3073, 0.9046, 0.4814, 0.5659, 0.2770])
tensor([0.9046, 0.5382, 0.5784])
tensor(0.5382)
0.5382081270217896


### **Tensor Reshaping**

In [36]:
x14 = torch.rand(4, 4)
print(x14)

x15 = x14.view(16)
print(x15)

x16 = x14.view(-1, 8) # -1 is automatically to right dimension -- if multiply of dimension not divisible by input, get error like x14.view(-1, 3)
print(x16, x16.size())

tensor([[0.5625, 0.6170, 0.0110, 0.5940],
        [0.0727, 0.2549, 0.8747, 0.9802],
        [0.0442, 0.8634, 0.2594, 0.3811],
        [0.9255, 0.2468, 0.8820, 0.2249]])
tensor([0.5625, 0.6170, 0.0110, 0.5940, 0.0727, 0.2549, 0.8747, 0.9802, 0.0442,
        0.8634, 0.2594, 0.3811, 0.9255, 0.2468, 0.8820, 0.2249])
tensor([[0.5625, 0.6170, 0.0110, 0.5940, 0.0727, 0.2549, 0.8747, 0.9802],
        [0.0442, 0.8634, 0.2594, 0.3811, 0.9255, 0.2468, 0.8820, 0.2249]]) torch.Size([2, 8])
