## **Import important Libraries**

In [2]:
import torch
import numpy as np

### **create Tensor in Torch**

In [3]:
# Empty tensor with 3 dimensions
x1 = torch.empty(4, 2, 3)
print(x1)

tensor([[[9.2755e-39, 1.0561e-38, 7.6225e-39],
         [8.9082e-39, 8.9082e-39, 9.6429e-39]],

        [[5.9694e-39, 1.0286e-38, 8.9081e-39],
         [8.9082e-39, 6.9796e-39, 9.0919e-39]],

        [[9.9184e-39, 7.3470e-39, 1.0194e-38],
         [1.0469e-38, 1.0010e-38, 8.4490e-39]],

        [[1.1112e-38, 9.5511e-39, 1.0102e-38],
         [7.3470e-39, 1.0653e-38, 1.0194e-38]]])


In [5]:
# Random tensor with 2 dimensions
x2 = torch.rand(2, 2)
print(x2)

tensor([[0.6758, 0.5371],
        [0.3255, 0.7261]])


In [6]:
# Zeroes tensor with 2 dimensions
x3 = torch.zeros(2, 2)
print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
# Ones tensor with 2 dimensions
x4 = torch.ones(2, 2)
print(x4)

tensor([[1., 1.],
        [1., 1.]])


### **Type of Tensor**

In [8]:
# default type of tensor is float32
x1.dtype

torch.float32

In [9]:
# you can set other type to tensor
x5 = torch.ones(2, 2, dtype=torch.int) # torch.int, torch.double, torch.float16
print(x5.dtype)

torch.int32


### **Size of Tensor**

In [10]:
x6 = torch.rand(2, 2)
print(x6.size())

torch.Size([2, 2])


### **Create tensor with list of data**

In [11]:
x7 = torch.tensor([2.5, 3, 1])
print(x7)

tensor([2.5000, 3.0000, 1.0000])


### **Basic Operations**

In [12]:
x8 = torch.rand(2, 2)
x9 = torch.rand(2, 2)

print(x8, x9)

# Addition
x10 = x9 + x8
x10 = torch.add(x9, x8)
x9.add_(x8)
print(x10, x9)

# Subtraction
x11 = x9 - x8
x11 = torch.sub(x9, x8)
x9.sub_(x8)
print(x11, x9)

# Multiplication
x12 = x9 * x8
x12 = torch.mul(x9, x8)
x9.mul_(x8)
print(x12, x9)

# Division
x12 = x9 / x8
x12 = torch.div(x9, x8)
x9.div_(x8)
print(x12, x9)

tensor([[0.7284, 0.6112],
        [0.7378, 0.6877]]) tensor([[0.7878, 0.5804],
        [0.7823, 0.8120]])
tensor([[1.5161, 1.1916],
        [1.5201, 1.4998]]) tensor([[1.5161, 1.1916],
        [1.5201, 1.4998]])
tensor([[0.7878, 0.5804],
        [0.7823, 0.8120]]) tensor([[0.7878, 0.5804],
        [0.7823, 0.8120]])
tensor([[0.5738, 0.3547],
        [0.5772, 0.5585]]) tensor([[0.5738, 0.3547],
        [0.5772, 0.5585]])
tensor([[0.7878, 0.5804],
        [0.7823, 0.8120]]) tensor([[0.7878, 0.5804],
        [0.7823, 0.8120]])


### **Tensor Slicing**

In [13]:
x13 = torch.rand(5, 3)
print(x13)

print(x13[:, 0]) # All rows and column 0

print(x13[1, :]) # row 1 and all columns

print(x13[1, 1]) # actual element
print(x13[1, 1].item()) # if tensor have one element, you can use .item() to get actual value

tensor([[0.6113, 0.7189, 0.5886],
        [0.6338, 0.6303, 0.8867],
        [0.7444, 0.8290, 0.2585],
        [0.0158, 0.9789, 0.9362],
        [0.3462, 0.9594, 0.7402]])
tensor([0.6113, 0.6338, 0.7444, 0.0158, 0.3462])
tensor([0.6338, 0.6303, 0.8867])
tensor(0.6303)
0.6302689909934998


### **Tensor Reshaping**

In [14]:
x14 = torch.rand(4, 4)
print(x14)

x15 = x14.view(16)
print(x15)

x16 = x14.view(-1, 8) # -1 is automatically to right dimension -- if multiply of dimension not divisible by input, get error like x14.view(-1, 3)
print(x16, x16.size())

tensor([[0.3732, 0.3925, 0.9322, 0.4545],
        [0.9504, 0.9478, 0.6997, 0.8741],
        [0.5007, 0.6492, 0.7806, 0.8764],
        [0.5173, 0.2368, 0.2302, 0.8607]])
tensor([0.3732, 0.3925, 0.9322, 0.4545, 0.9504, 0.9478, 0.6997, 0.8741, 0.5007,
        0.6492, 0.7806, 0.8764, 0.5173, 0.2368, 0.2302, 0.8607])
tensor([[0.3732, 0.3925, 0.9322, 0.4545, 0.9504, 0.9478, 0.6997, 0.8741],
        [0.5007, 0.6492, 0.7806, 0.8764, 0.5173, 0.2368, 0.2302, 0.8607]]) torch.Size([2, 8])


### **Tensor to Numpy**

In [16]:
#  convert tensor to numpy
x17 = torch.ones(5)
print(x17, x17.size())
x18 = x17.numpy()
print(x18, x18.shape)

# if run in cpu shared memory between tensor and numpy
x17.add_(1)
print(x17, x18)

tensor([1., 1., 1., 1., 1.]) torch.Size([5])
[1. 1. 1. 1. 1.] (5,)
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


### **Numpy to Tensor**

In [19]:
#  convert numpy to tensor
x19 = np.ones(5)
print(x19, x19.shape)
x20 = torch.from_numpy(x19)
print(x20, x20.size())

# if run in cpu shared memory between tensor and numpy
x19 += 1
print(x19, x20)

[1. 1. 1. 1. 1.] (5,)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) torch.Size([5])
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### **Use GPU -- Cuda**

In [21]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x21 = torch.ones(5, device=device)
    print(x21, x21.size())
    x22 = torch.ones(5)
    print(x22, x22.size())
    x22.to(device)
    x23 = x21 + x22
    print(x23, x23.size())
    
    # in gpu we can't use numpy and we must to back to cpu
    x23 = x23.to("cpu")
    x24 = x23.numpy()
    print(x24, x24.shape)